### ISSUE TITLE
No conformers generated

### ISSUE THREAD

**Issue by PatWalters** [shenoynikhil/ETFlow#15]
I ran the example from the README, but the returned molecules didn't have confomers. 

```python
from etflow import BaseFlow

model=BaseFlow.from_default(model="drugs-o3")
smiles_list = ['CN1C=NC2=C1C(=O)N(C(=O)N2C)C']
result_dict = model.predict(smiles_list, num_samples=3, as_mol=True)
for smi in smiles_list:
    confs = result_dict[smi]
    print([x.GetNumConformers() for x in confs])
```
returns
```
[0, 0, 0]
```

Am I doing something incorrectly?  This Is with Python 3.11.10 on OS-X 15.1.1.

**Comment by FNTwin** [comment]
Thank you for opening the issue @PatWalters.

I fixed it in #16 , small mistake from my end on a function. Now predict will work corretly + it will return a molecule object with N conformers instead of N molecule objects.

I will push a release tomorrow morning to have pypi synced with the fixed version.

Cristian
